units:
  padding: 4
  kx: u
  ky: u
  px: kx + padding
  py: ky + padding
  mcu_x: 18
  mcu_y: 23
  fillet: 2
points:
  zones:
    matrix:
       # Fix placement on KiCAD sheet.
      anchor:
        shift: [100, -150]
      columns:
        col1:
        col2:
        col3:
          rows.func.skip: true
      rows:
        func:
        bottom:
        home:
        top:
    thumbfan:
      anchor:
        ref: matrix_col3_func
        shift: [2, -2.75]
      columns:
        near:
          key.splay: -15
          rows.top.skip: true
        mid:
          key:
            splay: -5
            stagger: -1
            spread: kx + 0.5
        far:
          key:
            splay: -5
            stagger: -1
            spread: kx + 0.5
      rows:
        bottom:
        top:
outlines:
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
      bound: false
  plate:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_col1_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_col3_top
          shift: [0.5px + mcu_x + 2, 0.5py]
        - ref: matrix_col3_top
          shift: [0.5px + mcu_x + 2, -0.5py]
        - ref: thumbfan_far_top
          shift: [0.5px, 0.5py]
        - ref: thumbfan_far_bottom
          shift: [0.5px, -0.5py]
        - ref: matrix_col1_func
          shift: [-0.5px, -0.5py]
      fillet: fillet
    - what: circle
      where:
        ref: matrix_col1_func
        shift: [-6, -216]
      radius: 204
      operation: subtract
    - what: circle
      where:
        ref: matrix_col3_top
        shift: [71.5, 0.5py - mcu_y + 0.5]
      radius: 40
      operation: subtract
  quick_view: [plate, -keys]
pcbs:
  keydoku:
    template: kicad8
    outlines:
      main:
        outline: plate
      keycaps:
        outline: keys
        layer: Eco1.User
    footprints:
      promicro:
        what: achamian/rp_2040_zero
        where:
          ref: matrix_col3_top
          shift: [0.5px + 0.5mcu_x, 0.5py - 0.5mcu_y - 2]
        params:
          orientation: 'up'
      mx_switch:
        what: ceoloide/switch_mx
        where: true
        params:
          hotswap: true
          solder: false
          from: "{{column_net}}"
          to: "GND"
      # led:
      #   what: ceoloide/led_sk6812mini-e
      #   where: true
      #   params:
      #     side: F
