units:
  padding: 4
  kx: u
  ky: u
  px: kx + padding
  py: ky + padding
  mcu_x: 18
  mcu_y: 23
  fillet: 2
  led_pos_x: 0
  led_pos_y: -4.7
points:
  zones:
    matrix:
       # Fix placement on KiCAD sheet.
      anchor:
        shift: [100, -150]
      key:
        tags: [mx]
      columns:
        col1:
          rows:
            top:
              led_prev: LED_3
              led_next: LED_4
              net: P26
            home:
              led_prev: LED_4
              led_next: LED_5
              net: P15
            bottom:
              led_prev: LED_9
              led_next: LED_10
              net: P12
            func:
              led_prev: LED_10
              led_next: LED_11
              net: P9
        col2:
          rows:
            top:
              led_prev: LED_2
              led_next: LED_3
              net: P27
            home:
              led_prev: LED_5
              led_next: LED_6
              net: P14
            bottom:
              led_prev: LED_8
              led_next: LED_9
              net: P11
            func:
              led_prev: LED_11
              led_next: LED_12
              net: P8
        col3:
          rows:
            top:
              led_prev: LED_1
              led_next: LED_2
              net: P28
            home:
              led_prev: LED_6
              led_next: LED_7
              net: P13
            bottom:
              led_prev: LED_7
              led_next: LED_8
              net: P10
            func.skip: true
      rows:
        func:
        bottom:
        home:
        top:
    thumbfan:
      anchor:
        ref: matrix_col3_func
        shift: [2, -2.75]
      columns:
        near:
          key.splay: -15
          rows:
            thumb_t.skip: true
            thumb_b:
              tags: [choc]
              led_prev: LED_12
              led_next: LED_13
              net: P3
        mid:
          key:
            splay: -5
            stagger: -1
            spread: kx + 0.5
          rows:
            thumb_t:
              tags: [mx]
              led_prev: LED_16
              led_next: LED_17
              net: P7
            thumb_b:
              tags: [choc]
              led_prev: LED_13
              led_next: LED_14
              net: P4
        far:
          key:
            splay: -5
            stagger: -1
            spread: kx + 0.5
          rows:
            thumb_t:
              tags: [mx]
              led_prev: LED_15
              led_next: LED_16
              net: P6
            thumb_b:
              tags: [choc]
              led_prev: LED_14
              led_next: LED_15
              net: P5
      rows:
        thumb_b:
          key.tags: [mx]
        thumb_t:
    # mount points
    mounting_points:
      anchor:
        ref: matrix_col1_top
      key:
        width: 2
        height: 2
        tags: [mount]
      columns:
        hole_1:
          key.shift: [0, -0.5ky]
        hole_2:
          key.shift: [1kx, -0.5ky]
        hole_3:
          key.shift: [-2kx, -2.5ky]
        hole_4:
          key.shift: [0.925kx, -2.75ky]
    # bushes
    t_left_bush:
      anchor:
        ref: matrix_col1_top
        shift: [-0.25kx, 0.25ky]
      key.tags: [bushes]
    b_left_bush:
      anchor:
        ref: matrix_col1_func
        shift: [-0.25kx, -0.25ky]
      key.tags: [bushes]
    t_right_bush:
      anchor:
        ref: matrix_col3_top
        shift: [0.5kx + 0.75mcu_x, 0.25ky]
      key.tags: [bushes]
    m_right_bush:
      anchor:
        ref: thumbfan_far_thumb_t
        shift: [0.25kx, 0.25ky]
      key.tags: [bushes]
    b_right_bush:
      anchor:
        ref: thumbfan_far_thumb_b
        shift: [0.25kx, -0.25ky]
      key.tags: [bushes]
outlines:
  keys:
    - what: rectangle
      where: /(mx|choc)/
      size: [kx-0.5,ky-0.5]
      bound: false
  plate:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_col1_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_col3_top
          shift: [0.5px + mcu_x + 2, 0.5py]
        - ref: matrix_col3_top
          shift: [0.5px + mcu_x + 2, -0.5py]
        - ref: thumbfan_far_thumb_t
          shift: [0.5px, 0.5py]
        - ref: thumbfan_far_thumb_b
          shift: [0.5px, -0.5py]
        - ref: matrix_col1_func
          shift: [-0.5px, -0.5py]
      fillet: fillet
    - what: circle
      where:
        ref: matrix_col1_func
        shift: [-6, -216]
      radius: 204
      operation: subtract
    - what: circle
      where:
        ref: matrix_col3_top
        shift: [71.5, 0.5py - mcu_y + 0.5]
      radius: 40
      operation: subtract
  choc_cluster:
    - what: polygon
      operation: stack
      points:
        - ref: thumbfan_near_thumb_b
          shift: [-0.5px, 0.5ky]
        - ref: thumbfan_near_thumb_b
          shift: [0.5kx, 0.5ky]
        - ref: thumbfan_mid_thumb_b
          shift: [0.5kx, 0.5ky]
        - ref: thumbfan_far_thumb_b
          shift: [px, 0.5ky]
        - ref: thumbfan_far_thumb_b
          shift: [px, -py]
        - ref: thumbfan_near_thumb_b
          shift: [-0.5px, -py]
      fillet: fillet
    - what: outline
      name: plate
      operation: intersect
  top_plate:
    - what: outline
      name: plate
    - what: rectangle
      where:
        ref: matrix_col3_top
        shift: [14 + 0.5px, -23 + 0.5py]
      operation: subtract
      size: [30, 46]
      fillet: fillet
  mx_switch_holes:
    - what: rectangle
      where: /mx/
      size: 14
  mx_switch_notch_clearance:
    - what: rectangle
      where: /mx/
      size: 15
  _mx_component_clearance:
    - what: polygon
      where: /mx/
      operation: stack
      points:
        - shift: [0, -7]
        - shift: [-3.5, 0]
        - shift: [-5.25, 8]
        - shift: [0, 6.25]
        - shift: [17, 0]
        - shift: [0, -5.25]
        - shift: [-5, -9]
  _choc_component_clearance:
    - what: polygon
      where: /choc/
      operation: stack
      points:
        - shift: [-7, -7]
        - shift: [0, 17]
        - shift: [17, 0]
        - shift: [0, -17]
  _mcu_clearance:
    - what: rectangle
      where:
        ref: matrix_col3_top
        shift: [kx + 1.5, -0.5padding]
      size: [mcu_x + 1, mcu_y + 1]
  component_clearances: [_mx_component_clearance, _choc_component_clearance, _mcu_clearance]
  bushes:
    - what: circle
      radius: 5.1
      where: /bushes/
  choc_switch_holes:
    - what: rectangle
      where: /choc/
      size: 13.9
  choc_switch_notch_clearance:
    - what: rectangle
      where: /choc/
      size: 15
  m2_heat_inserts:
    - what: circle
      where: /mounting_points/
      radius: 1.55
  m2_hole:
    - what: circle
      where: /mounting_points/
      radius: 1.1
  m2_nut_head:
    - what: circle
      where: /mounting_points/
      radius: 2.2
  quick_view: [plate, -bushes]
pcbs:
  keydoku:
    template: kicad8
    outlines:
      main:
        outline: plate
      clearances:
        outline: component_clearances
        layer: Eco1.User
    footprints:
      mcu:
        what: achamian/rp_2040_zero
        where:
          ref: matrix_col3_top
          shift: [0.5px + 0.5mcu_x, 0.5py - 0.5mcu_y - 2]
        params:
          orientation: 'up'
          P29: LED_1
      mx_switch:
        what: ceoloide/switch_mx
        where: /mx/
        params:
          hotswap: true
          solder: false
          from: "GND"
          to: "{{net}}"
      choc_swich:
        what: ceoloide/switch_choc_v1_v2
        where: /choc/
        params:
          hotswap: true
          include_plated_holes: false
          choc_v2_support: true
          from: "GND"
          to: "{{net}}"
      per_key_led_rotated:
        what: ceoloide/led_sk6812mini-e
        where: /(top|bottom|thumb_t)/
        params:
          side: B
          P1: VCC5V
          P2: "{{led_next}}" # DOUT
          P3: GND
          P4: "{{led_prev}}" # DIN
        adjust:
          shift: [led_pos_x, led_pos_y]
          rotate: 180
      per_key_led:
        what: ceoloide/led_sk6812mini-e
        where: /(home|func|thumb_b)/
        params:
          side: B
          P1: VCC5V
          P2: "{{led_next}}" # DOUT
          P3: GND
          P4: "{{led_prev}}" # DIN
        adjust:
          shift: [led_pos_x, led_pos_y]
      mounting_holes:
        what: ceoloide/mounting_hole_npth
        where: /mount/
cases:
  _bottom_clearances:
    - name: component_clearances
      extrude: 2
      shift: [0, 0, 1.5]
  _bottom_bushes:
    - name: bushes
      extrude: 1
  _bottom_m2_hole:
    - name: m2_hole
      extrude: 3.5
  _bottom_m2_nut_head:
    - name: m2_nut_head
      extrude: 2
  _bottom_plate:
    - name: plate
      extrude: 3.5
  bottom_case:
    - what: case
      name: _bottom_plate
      operation: add
    - what: case
      name: _bottom_clearances
      operation: subtract
    - what: case
      name: _bottom_bushes
      operation: subtract
    - what: case
      name: _bottom_m2_hole
      operation: subtract
    - what: case
      name: _bottom_m2_nut_head
      operation: subtract

